<?php

namespace AGPlatformBundle\Repository;

/**
 * VannonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VannonceRepository extends \Doctrine\ORM\EntityRepository
{
}
